### ISSUE TITLE
container 0.32 stops reposnding after a few minutes

### ISSUE THREAD

**Issue by arshesney** [Snd-R/komf#134]
After updating komf deployment to the latest 0.32 version, it stops responding to requests after a few minutes. Trying curl to the address hangs forever.

No messages appear in log.
[Explore-logs-2024-02-29 12 26 52.txt](https://github.com/Snd-R/komf/files/14447221/Explore-logs-2024-02-29.12.26.52.txt)

Version 0.31.8 does not have the issue.

Container is deployed on a raspberry pi 4, with k3s, ram used is around 300Mb

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komf
  namespace: kavita
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: komf
  template:
    metadata:
      labels:
        app: komf
    spec:
      containers:
      - name: komf
        image: sndxr/komf:latest
        ports:
        - name: komf
          containerPort: 8085
        envFrom:
        - configMapRef:
            name: kavita-env
        volumeMounts:
        - name: komf-data
          mountPath: /config
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 2Gi
      volumes:
      - name: komf-data
        persistentVolumeClaim:
          claimName: komf-data
```
environment:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kavita-env
  namespace: kavita
data:
  TZ: Europe/Rome
  SMTP_HOST: my.mail.host
  SMTP_PORT: "25"
  SEND_ADDR: <snip>
  DISP_NAME: <snip>
  ALLOW_SENDTO: "false"
  KOMF_KOMGA_BASE_URI: http://komga:25600
  KOMF_KOMGA_USER: <snip>
  KOMF_KOMGA_PASSWORD: <snip>
  KOMF_LOG_LEVEL: DEBUG
```
