### ISSUE TITLE
Komf not fetching "ja-ro" from Mangadex

### ISSUE THREAD

**Issue by Xian-beep** [Snd-R/komf#142]
Since the last two updates it seems like "ja-ro" doesn't fetch anymore from Mangadex as a source. It should in this case display as "Sousou no Frieren" and not "Frieren at the Funeral". I have more examples in my library, some that just have the Japanese characters and not ja-ro or en.

<details><summary>Mangadex:</summary><p>

![image](https://github.com/Snd-R/komf/assets/83923843/d490e46c-50f0-4098-bd63-7ae59b288d4e)

</p></details>

<details><summary>Komga with komf configured to use "ja-ro" as main title:</summary><p>

![image](https://github.com/Snd-R/komf/assets/83923843/86ac6645-4b5e-4a43-a9d7-9d5a4f09c342)

</p></details>

Configuration snippet for the library in question:

```
0ER2MAAPBRZK6:
     updateModes: [ API ]
     aggregate: false
     bookCovers: true
     seriesCovers: true
     overrideExistingCovers: true
     postProcessing:
          seriesTitle: true
          seriesTitleLanguage: "ja-ro"
          alternativeSeriesTitles: true
          alternativeSeriesTitleLanguages:
             - "en"
             - "ja"
 ```
