### ISSUE TITLE
[Feature Request] Kavita - Allow cover locking

### ISSUE THREAD

**Issue by CPU-Blanc** [Snd-R/komf#166]
Hello!
Been using komf for a while now and it was working great until recently when all my cover images generated by komf are being replaced by the first page of the first chapter. A little poking and it seems as though komf _is_ updating the series cover image as requested, but kavita then rescans the series and generates a new cover image, removing the old one.
I'd like to have komf manage all of my cover images as it used to. Could a new config option be made to allow komf to lock the kavita cover image to prevent kavita messing with it? Unless this is an unintentional regression?

My current config

```
kavita:
  eventListener:
    enabled: true # if disabled will not connect to kavita and won't pick up newly added entries
    metadataLibraryFilter: [ ]  # listen to all events if empty
    metadataSeriesExcludeFilter: ["157"]
    notificationsLibraryFilter: [ ]
  notifications:
    libraries: [ ]  # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
  metadataUpdate:
    default:
      libraryType: "MANGA" # Can be "MANGA", "NOVEL" or "COMIC". Hint to help better match book numbers
      updateModes: [ API, COMIC_INFO ] # can use multiple options at once. available options are API, COMIC_INFO
      aggregate: true # if enabled will search and aggregate metadata from all configured providers
      mergeTags: false # if true and aggregate is enabled will merge tags from all providers
      mergeGenres: false # if true and aggregate is enabled will merge genres from all providers
      bookCovers: true #update book thumbnails
      seriesCovers: true #update series thumbnails
      overrideExistingCovers: true
      postProcessing:
        seriesTitle: true #update series title
        seriesTitleLanguage: "en" # series title update language. If empty chose first matching title
        alternativeSeriesTitles: false # use other title types as alternative title option
        alternativeSeriesTitleLanguages: # alternative title language. Only first language is used. Use single value for consistency
          - "ja-ro"
        orderBooks: true # will order books using parsed volume or chapter number. works only with COMIC_INFO
        languageValue: # set default language for series. Must use BCP 47 format e.g. "en"
```
