### ISSUE TITLE
MangaDex provider to use series title

### ISSUE THREAD

**Issue by xcymax** [Snd-R/komf#169]
As per #142 
This behaviour of taking the first matching alternative title instead of the main one really confused me before digging deeper.

With 
```
     postProcessing:
        seriesTitle: true
        seriesTitleLanguage: "en"
        fallbackToAltTitle: false
```
I expected it to use the `en` series title only but instead it ignores it and sets to the first `en` altTitle if it exists - even with `fallbackToAltTitle: false`

https://github.com/Snd-R/komf/issues/142#issuecomment-2041135950
> Also Komf ignores main title completely and only takes altTitles since main title often tagged wrong.

I think if the metadata source is wrong then let it be wrong 😛

Anyway requesting this behaviour be reverted or at least configurable to use main titles again thanks.
