### ISSUE TITLE
No metadata providers enabled. You will not be able to get new metadata

### ISSUE THREAD

**Issue by EzraSchutte** [Snd-R/komf#194]
Hey I'm new to komf and kavita I'm trying to get metadata for my manga (mainly thumbnails tbh) and its not working I also can't really figure out the documentation. Here's my setup I'm using docker on debian 12 for both applications kavita works fine. Komf looks like its working but I don't see any changes to metadata even after deleting library and remaking it. I blurred out the apiKey.

application.yml:
```
kavita:
  baseUri: "http://192.168.1.254:5000" #or env:KOMF_KAVITA_BASE_URI
  apiKey: "------------------" #or env:KOMF_KAVITA_API_KEY
  eventListener:
    enabled: true # if disabled will not connect to kavita and won't pick up newly added entries
    metadataLibraryFilter: [ ]  # listen to all events if empty
    metadataSeriesExcludeFilter: [ ]
    notificationsLibraryFilter: [ ] # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
  metadataUpdate:
    default:
      libraryType: "MANGA" # Can be "MANGA", "NOVEL" or "COMIC". Hint to help better match book numbers
      updateModes: [ API ] # can use multiple options at once. available options are API, COMIC_INFO
      aggregate: false # if enabled will search and aggregate metadata from all configured providers
      mergeTags: false # if true and aggregate is enabled will merge tags from all providers
      mergeGenres: false # if true and aggregate is enabled will merge genres from all providers
      bookCovers: false #update book thumbnails
      seriesCovers: false #update series thumbnails
      overrideExistingCovers: true # if false will upload but not select new cover if another cover already exists
      lockCovers: true # lock cover images so that kavita does not change them
      postProcessing:
        seriesTitle: false #update series title
        seriesTitleLanguage: "en" # series title update language. If empty chose first matching title
        alternativeSeriesTitles: false # use other title types as alternative title option
        alternativeSeriesTitleLanguages: # alternative title language. Only first language is used. Use single value for consistency
          - "ja-ro"
        orderBooks: false # will order books using parsed volume or chapter number. works only with COMIC_INFO
        languageValue: # set default language for series. Must use BCP 47 format e.g. "en"

  metadataProviders:
    default:
      mangaUpdates:
        priority: 10
        enabled: true
        authorRoles: [ "WRITER" ]
        artistRoles: [ "PENCILLER","INKER","COLORIST","LETTERER","COVER" ]
        seriesMetadata:
          status: true
          title: true
          titleSort: true
          summary: true
          publisher: true
          readingDirection: true
          ageRating: true
          language: true
          genres: true
          tags: true
          totalBookCount: true
          authors: true
          thumbnail: true
          releaseDate: true
          links: true
          score: true
          books: true
          useOriginalPublisher: true # prefer original publisher and volume information if source has data about multiple providers. If false will use english or other available publisher
        bookMetadata:
          title: true
          summary: true
          number: true
          numberSort: true
          releaseDate: true
          authors: true
          tags: true
          isbn: true
          links: true
          thumbnail: true
  database:
    file: ./database.sqlite # database file location.
```
docker compose up
```
komf  | 02:05:05.064 [main] WARN snd.komf.app.config.ConfigLoader -- No metadata providers enabled. You will not be able to get new metadata
komf  | 02:05:06.356 [main] INFO snd.komf.mediaserver.kavita.KavitaEventHandler -- connecting to Kavita event listener http://192.168.1.254:5000/hubs/messages
komf  | 02:05:06.397 [main] INFO io.ktor.server.Application -- Autoreload is disabled because the development mode is off.
komf  | 02:05:06.492 [OkHttp http://192.168.1.254:5000/...] INFO http.logging -- --> POST http://192.168.1.254:5000/api/plugin/authenticate?apiKey=--------------&pluginName=Komf (0-byte body)
komf  | 02:05:06.527 [main] INFO io.ktor.server.Application -- Application started in 0.141 seconds.
komf  | 02:05:06.551 [DefaultDispatcher-worker-2] INFO io.ktor.server.Application -- Responding at http://0.0.0.0:8085
komf  | 02:05:06.558 [OkHttp http://192.168.1.254:5000/...] INFO http.logging -- <-- 200 OK http://192.168.1.254:5000/api/plugin/authenticate?apiKey=---------------------------&pluginName=Komf (65ms, unknown-length body)
komf  | 02:05:06.634 [OkHttp http://192.168.1.254:5000/...] INFO com.microsoft.signalr.WebSocketTransport -- WebSocket transport connected to: ws://192.168.1.254:5000/hubs/messages?id=g-dvQ1w9CCzSuPwJ79Et-w.
komf  | 02:05:06.649 [OkHttp http://192.168.1.254:5000/...] INFO com.microsoft.signalr.HubConnection -- HubConnection started.
```
If I try to use the userscript I get this error after saving in kavita

Request failed with status code 422

Screen of the database
![image](https://github.com/user-attachments/assets/815264ec-4835-4690-b9d4-338d8a984dae)
