### ISSUE TITLE
Kavita - Komf -> Identify Server Error 500

### ISSUE THREAD

**Issue by Zeroflix** [Snd-R/komf#202]
Hey,
so I installed komf on my synology NAS with docker compose and I am running into some issues.
When I connect to the http://192.168.0.250:8085 (or kavita.simsn.com) I get the following:

![Image](https://github.com/user-attachments/assets/29bf1359-c82c-4709-bde4-d67e46cb9d66)

![Image](https://github.com/user-attachments/assets/0d99fd99-0356-4094-b95c-e845b8992dc2)

![Image](https://github.com/user-attachments/assets/04eaa91f-92c1-4b0f-bdd1-a1115b9b1f85)

This is my docker compose YAML:

```
services:
    kavita:
        image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
        container_name: kavita
        volumes:
            - /volume1/docker/qbittorrent/downloads/Manga:/manga
            - /volume1/docker/qbittorrent/downloads/Comics:/comics
            - /volume1/docker/qbittorrent/downloads/Buecher:/buecher
            - /volume1/docker/kavita/:/kavita/config     # /kavita/config must not be changed
        environment:
            - TZ=Your/Timezone
            - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
        ports:
            - "5000:5000"
            - "8085:8085"
        restart: unless-stopped
    komf:
        image: sndxr/komf:latest
        container_name: komf
        user: "1000:1000"
        environment:
            - KOMF_KAVITA_BASE_URI=http://kavita:5000
            - KOMF_KAVITA_API_KEY=XXXXXXXXXXXXX
            - KOMF_LOG_LEVEL=INFO
            # optional jvm options. Example config for low memory usage. Runs guaranteed cleanup up every 3600000ms(1hour)
            - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
        volumes:
            - /volume1/docker/kavita/komf:/config #path to directory with application.yml and database file
        network_mode: "service:kavita"
        restart: unless-stopped
```

This is my application.yml file:

```
kavita:
  baseUri: env:KOMF_KAVITA_BASE_URI #or env:KOMF_KAVITA_BASE_URI
  apiKey: "XXXXXXXXX" #or env:KOMF_KAVITA_API_KEY
  eventListener:
    enabled: true # if disabled will not connect to kavita and won't pick up newly added entries
    metadataLibraryFilter: [ ]  # listen to all events if empty
    metadataSeriesExcludeFilter: [ ]
    notificationsLibraryFilter: [ ] # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
  metadataUpdate:
    default:
      libraryType: "MANGA" # Can be "MANGA", "NOVEL" or "COMIC". Hint to help better match book numbers
      updateModes: [ API ] # can use multiple options at once. available options are API, COMIC_INFO
      aggregate: true # if enabled will search and aggregate metadata from all configured providers
      mergeTags: true # if true and aggregate is enabled will merge tags from all providers
      mergeGenres: true # if true and aggregate is enabled will merge genres from all providers
      bookCovers: true #update book thumbnails
      seriesCovers: true #update series thumbnails
      overrideExistingCovers: true # if false will upload but not select new cover if another cover already exists
      lockCovers: true # lock cover images so that kavita does not change them
      postProcessing:
        seriesTitle: true #update series title
        seriesTitleLanguage: "en" # series title update language. If empty chose first matching title
        alternativeSeriesTitles: false # use other title types as alternative title option
        alternativeSeriesTitleLanguages: # alternative title language. Only first language is used. Use single value for consistency
          - "ja-ro"
        orderBooks: false # will order books using parsed volume or chapter number. works only with COMIC_INFO
        languageValue: # set default language for series. Must use BCP 47 format e.g. "en"

database:
  file: ./database.sqlite # database file location.

metadataProviders:
  malClientId: "XXXXXXXXXXX" # required for mal provider. See https://myanimelist.net/forum/?topicid=1973077 env:KOMF_METADATA_PROVIDERS_MAL_CLIENT_ID
  comicVineApiKey: # required for comicVine provider https://comicvine.gamespot.com/api/ env:KOMF_METADATA_PROVIDERS_COMIC_VINE_API_KEY
  bangumiToken: # bangumi provider require a token to show nsfw items https://next.bgm.tv/demo/access-token  env:KOMF_METADATA_PROVIDERS_BANGUMI_TOKEN
  defaultProviders:
    mangaUpdates:
      priority: 10
      enabled: true
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
      authorRoles: [ "WRITER" ] # roles that will be mapped to author role
      artistRoles: [ "PENCILLER","INKER","COLORIST","LETTERER","COVER" ] # roles that will be mapped to artist role
    mal:
      priority: 20
      enabled: true
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
    nautiljon:
      priority: 30
      enabled: false
    aniList:
      priority: 40
      enabled: false
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA. MANGA type includes everything except novels
      tagsScoreThreshold: 60 # tags with this score or higher will be included
      tagsSizeLimit: 15 # amount of tags that will be included
    yenPress:
      priority: 50
      enabled: false
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
    kodansha:
      priority: 60
      enabled: false
    viz:
      priority: 70
      enabled: false
    bookWalker:
      priority: 80
      enabled: false
      mediaType: "MANGA" # filter used in matching. Can be NOVEL or MANGA.
    mangaDex:
      priority: 90
      enabled: false
      coverLanguages:
        - "en"
        - "ja"
    bangumi: # Chinese metadata provider. https://bgm.tv/
      priority: 100
      enabled: false
    comicVine: # https://comicvine.gamespot.com/ requires API key. Experimental provider, can mismatch issue numbers
      priority: 110
      enabled: false
    hentag:
      priority: 120
      enabled: false
server:
  port: 8085 # or env:KOMF_SERVER_PORT
```

It seems like I am connected:

![Image](https://github.com/user-attachments/assets/024d0d63-6c1f-4594-be23-462b8dd42d40)

![Image](https://github.com/user-attachments/assets/94c49875-133e-45ee-813a-d373abde9cb3)

What am I doing wrong here?
