### ISSUE TITLE
Error : Required value 'alternateTitles' missing at $.metadata

### ISSUE THREAD

**Issue by JamesDAdams** [Snd-R/komf#42]
Hi, i ave this error when i add a new book in komga : 

> 15:34:15.453 [main] WARN org.snd.config.ConfigLoader - No metadata providers enabled. You will not be able to get new metadata
> 15:34:16.772 [main] INFO io.javalin.Javalin - Starting Javalin ...
> 15:34:16.947 [main] INFO io.javalin.Javalin - Listening on http://localhost:8085/
> 15:34:16.961 [main] INFO io.javalin.Javalin - You are running Javalin 5.2.0 (released November 20, 2022).
> 15:34:16.963 [main] INFO io.javalin.Javalin - Javalin started in 191ms \o/
> 15:34:18.957 [OkHttp http://192.168.1.100:10110/...] INFO org.snd.mediaserver.komga.KomgaEventListener - connected to komga on http://192.168.1.100:10110/
> Exception in thread "komf-event-listener-1" com.squareup.moshi.JsonDataException: Required value 'alternateTitles' missing at $.metadata
> at com.squareup.moshi.internal.Util.missingProperty(Util.java:660)
> at org.snd.mediaserver.komga.model.dto.KomgaSeriesMetadataJsonAdapter.fromJson(KomgaSeriesMetadataJsonAdapter.kt:154)
> at org.snd.mediaserver.komga.model.dto.KomgaSeriesMetadataJsonAdapter.fromJson(KomgaSeriesMetadataJsonAdapter.kt:25)
> at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
> at org.snd.mediaserver.komga.model.dto.KomgaSeriesJsonAdapter.fromJson(KomgaSeriesJsonAdapter.kt:72)
> at org.snd.mediaserver.komga.model.dto.KomgaSeriesJsonAdapter.fromJson(KomgaSeriesJsonAdapter.kt:22)
> at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
> at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:205)
> at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
> at org.snd.mediaserver.komga.KomgaClient.getSeries-4X2igCU(KomgaClient.kt:269)
> at org.snd.mediaserver.komga.KomgaMediaServerClientAdapter.getSeries-iuyh2M0(KomgaMediaServerClientAdapter.kt:36)
> at org.snd.mediaserver.MetadataService.matchSeriesMetadata-iuyh2M0(MetadataService.kt:108)
> at org.snd.mediaserver.komga.KomgaEventListener.processEvents(KomgaEventListener.kt:132)
> at org.snd.mediaserver.komga.KomgaEventListener.onEvent$lambda$6$lambda$5(KomgaEventListener.kt:118)
> at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> at java.base/java.lang.Thread.run(Unknown Source)

My config : 

```
komga:
  baseUri: http://192.168.1.100:10110 #or env:KOMF_KOMGA_BASE_URI
  komgaUser: Komf@Komf.fr #or env:KOMF_KOMGA_USER
  komgaPassword: password #or env:KOMF_KOMGA_PASSWORD
  eventListener:
    enabled: true # if disabled will not connect to komga and won't pick up newly added entries
    libraries: [ ]  # listen to all events if empty
  notifications:
    libraries: [ ]  # Will send notifications if any notification source is enabled. If empty will send notifications for all libraries
discord:
  webhooks: [https://discord.com/api/webhooks/MASQUED
  seriesCover: true # include series cover in message. Requires imgurClientId
  imgurClientId: MASQUED
  templatesDirectory: "./" #path to a directory with discordWebhook.vm template
database:
  file: ./database.sqlite #database file location.
server:
  port: 8085 #or env:KOMF_SERVER_PORT
logLevel: INFO #or env:KOMF_LOG_LEVEL
```
And i don't receive the notif on discord

Thanks
