### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by eswiig** [Snd-R/komf#58]
Hi, sorry I'm kind of new to this, 

I managed to run komf in a portainer stack / docker compose, provided baseurl, komgauser and komgapassword

I then created application.yml in :/config and provided baseurl, komgauser and komgapassword
what's the next step to get komf up and running? 

how do I know if it works as it should?

**Comment by Snd-R** [comment]
If you enabled event listener It will automatically search metadata for newly added series and books
To update metadata of existing series you can do any of the following options:
- https://github.com/Snd-R/komf/wiki/Komf-UI-using-Userscript 
- https://github.com/Snd-R/komf/wiki/Command-line-options
- https://github.com/Snd-R/komf/wiki/Http-endpoints

**Comment by eswiig** [comment]
I understand it will be hard to support everyone's config, but maybe you can give me some hints on what to do next.

I'm running Komga on a Portainer stack with Traefik on my local network behind a firewall.

This is what the container log says: 
00:01:34.586 [main] INFO io.javalin.Javalin -- Starting Javalin ...
00:01:34.753 [main] INFO io.javalin.Javalin -- Listening on http://localhost:8085/
00:01:34.772 [main] INFO io.javalin.Javalin -- You are running Javalin 5.4.2 (released March 6, 2023).
00:01:34.774 [main] INFO io.javalin.Javalin -- Javalin started in 188ms \o/

supposedly it's up and running, however the tampermonkey script is not detected/active on the site. 
I added my url to @include in the tampermonkey script.

since this is all locally on the network, do I need to open any ports externally?
I don't know how to use http endpoints or command line options.

**Comment by Dracon23** [comment]
Have you properly labeled your container for traefik usage?

My config for a quick example. (Works internally, have yet to test it externally, won't do so for a while.)
```
  komf:
    image: sndxr/komf:latest
    container_name: komf
    user: "1000:1000"
    volumes:
      - /path/to/komf/config:/config #path to directory with application.yml and database file
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.komf_internal.rule=(Host(`your.komf.url`))"
      - "traefik.http.routers.komf_internal.service=komf"
      - "traefik.http.routers.komf_internal.entrypoints=web"
      - "traefik.http.services.komf.loadbalancer.server.port=8085"
 ```

**Comment by eswiig** [comment]
> Have you properly labeled your container for traefik usage?
> 
> My config for a quick example. (Works internally, have yet to test it externally, won't do so for a while.)
> 
> ```
>   komf:
>     image: sndxr/komf:latest
>     container_name: komf
>     user: "1000:1000"
>     volumes:
>       - /path/to/komf/config:/config #path to directory with application.yml and database file
>     restart: unless-stopped
>     labels:
>       - "traefik.enable=true"
>       - "traefik.http.routers.komf_internal.rule=(Host(`your.komf.url`))"
>       - "traefik.http.routers.komf_internal.service=komf"
>       - "traefik.http.routers.komf_internal.entrypoints=web"
>       - "traefik.http.services.komf.loadbalancer.server.port=8085"
> ```

Originally I had not done so, thanks... I did add it though, but nothing changed.

**Comment by eswiig** [comment]
edit: think I got it working thanks to @Dracon23 , I forgot to enter komf into traefik portainer stack. at least, now I have the komf icons.

**Comment by Dracon23** [comment]
I haven't tried that yet, but as long as your library is accessible for komf, and your browser can access your user script, it should work.

**Comment by eswiig** [comment]
I somehow managed to mess it up and lost the icons again, all I really did was to restart trafik I think.

EDIT - You will have to point that url to your traefik instance, and use the Host you setup in the traefik rule. Otherwise traefik will have no clue where to send that request.

Do you mean I need a new url that's different from my komga domain url?

example: my komga domain is abc.com, I need a new domain for komf?

**Comment by Dracon23** [comment]
A subdomain(ex: komf.abc.com) would suffice, as long as you can reach your traefik instance under it

**Comment by eswiig** [comment]
@Snd-R could you please elaborate on the conditions for the komf icons and komf settings to show up?

I had them, but then they disappeared and now they won't come back.

It would help me troubleshoot the issue.

**Comment by Snd-R** [comment]
Userscript is only loaded on websites that you define in include section
![image](https://user-images.githubusercontent.com/76580768/236694825-4d129c1c-2592-4d76-9e1c-ec8dd12c762e.png)
You should set it to your domain name that you configured for komga (the address that you use to access komga in browser)

**Comment by Snd-R** [comment]
Then in connection tab of userscript you need to define address of komf instance. If you setup a domain name in traefik for komf then use that domain name 
Make sure that komf's domain name is accessible, it should at least display not found message if you just try to visit the base url

**Comment by Snd-R** [comment]
I see that you had the script running but without any elements showing up.
Userscript checks if the name of the tab contains work Komga and if it does loads the elements

**Comment by Snd-R** [comment]
here's a basic example of compose that works for me
```yml
version: "3.3"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  komga:
    image: gotson/komga:latest
    container_name: komga-test
    volumes:
      - ./komga/config:/config
      - ./library:/data
    user: "1000:1000"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.komga.rule=Host(`komga.localhost`)"
      - "traefik.http.routers.komga.entrypoints=web"
      - "traefik.http.services.komga.loadbalancer.server.port=8080"

  komf:
    image: sndxr/komf:latest
    container_name: komf-test
    user: "1000:1000"
    volumes:
      - ./komf:/config
      - ./library:/data
      - ./library:/manga
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.komf.rule=Host(`komf.localhost`)"
      - "traefik.http.routers.komf.entrypoints=web"
      - "traefik.http.services.komf.loadbalancer.server.port=8085"
```

tampermonkey include 
![image](https://user-images.githubusercontent.com/76580768/236696343-ed1d1cbd-2fb7-49ff-997d-006a4c41ae50.png)

komf's connection settings
![image](https://user-images.githubusercontent.com/76580768/236696378-21876b02-750b-473c-85cc-cb23f052a661.png)
